# Generated by Django 3.2.24 on 2026-05-20 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='作业标题')),
                ('description', models.TextField(verbose_name='作业描述')),
                ('due_date', models.DateTimeField(verbose_name='截止日期')),
                ('max_score', models.IntegerField(default=100, verbose_name='满分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '作业',
                'verbose_name_plural': '作业',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='章节标题')),
                ('description', models.TextField(blank=True, verbose_name='章节描述')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('duration_minutes', models.IntegerField(default=0, verbose_name='章节时长(分钟)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '课程章节',
                'verbose_name_plural': '课程章节',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='课程标题')),
                ('description', models.TextField(verbose_name='课程描述')),
                ('cover_image', models.CharField(blank=True, max_length=500, verbose_name='封面图片')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='结束日期')),
                ('duration_hours', models.IntegerField(default=0, verbose_name='课程时长(小时)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '培训课程',
                'verbose_name_plural': '培训课程',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200, verbose_name='课程名称')),
                ('department', models.CharField(max_length=100, verbose_name='部门')),
                ('position', models.CharField(max_length=100, verbose_name='职位')),
                ('reason', models.TextField(verbose_name='报名理由')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '报名',
                'verbose_name_plural': '报名',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(blank=True, max_length=200, verbose_name='课程名称')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='部门')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='职位')),
                ('reason', models.TextField(blank=True, verbose_name='报名理由')),
                ('draft_data', models.JSONField(default=dict, verbose_name='草稿数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '报名草稿',
                'verbose_name_plural': '报名草稿',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='用户名')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='TrainingNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='通知标题')),
                ('content', models.TextField(verbose_name='通知内容')),
                ('priority', models.CharField(choices=[('low', '低'), ('normal', '普通'), ('high', '高'), ('urgent', '紧急')], default='normal', max_length=20, verbose_name='优先级')),
                ('is_published', models.BooleanField(default=False, verbose_name='是否发布')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.course', verbose_name='关联课程')),
            ],
            options={
                'verbose_name': '培训通知',
                'verbose_name_plural': '培训通知',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='enrollment_files/', verbose_name='文件')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_size', models.BigIntegerField(verbose_name='文件大小')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.enrollmentdraft', verbose_name='草稿')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.enrollment', verbose_name='报名')),
            ],
            options={
                'verbose_name': '报名文件',
                'verbose_name_plural': '报名文件',
            },
        ),
        migrations.AddField(
            model_name='enrollmentdraft',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user', verbose_name='用户'),
        ),
        migrations.CreateModel(
            name='Courseware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='课件标题')),
                ('type', models.CharField(choices=[('video', '视频'), ('document', '文档'), ('image', '图片'), ('other', '其他')], default='document', max_length=20, verbose_name='课件类型')),
                ('file_url', models.CharField(max_length=500, verbose_name='文件URL')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('duration_minutes', models.IntegerField(default=0, verbose_name='视频时长(分钟)')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coursewares', to='api.chapter', verbose_name='章节')),
            ],
            options={
                'verbose_name': '课件',
                'verbose_name_plural': '课件',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enrolled', '已报名'), ('in_progress', '学习中'), ('completed', '已完成'), ('cancelled', '已取消')], default='enrolled', max_length=20, verbose_name='状态')),
                ('progress_percent', models.IntegerField(default=0, verbose_name='学习进度(%)')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='报名时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='api.course', verbose_name='课程')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to='api.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '课程选课',
                'verbose_name_plural': '课程选课',
                'ordering': ['-enrolled_at'],
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_courses', to='api.user', verbose_name='讲师'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='api.course', verbose_name='课程'),
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='提交内容')),
                ('attachment_url', models.CharField(blank=True, max_length=500, verbose_name='附件URL')),
                ('status', models.CharField(choices=[('submitted', '已提交'), ('grading', '批改中'), ('graded', '已批改')], default='submitted', max_length=20, verbose_name='状态')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='得分')),
                ('feedback', models.TextField(blank=True, verbose_name='批改反馈')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='批改时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='api.assignment', verbose_name='作业')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='api.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '作业提交',
                'verbose_name_plural': '作业提交',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.course', verbose_name='课程'),
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(verbose_name='评分(1-5)')),
                ('content', models.TextField(verbose_name='评价内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='api.courseenrollment', verbose_name='选课')),
            ],
            options={
                'verbose_name': '课程评价',
                'verbose_name_plural': '课程评价',
                'unique_together': {('enrollment',)},
            },
        ),
        migrations.CreateModel(
            name='ChapterProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chapter', verbose_name='章节')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_progress', to='api.courseenrollment', verbose_name='选课')),
            ],
            options={
                'verbose_name': '章节学习进度',
                'verbose_name_plural': '章节学习进度',
                'ordering': ['chapter__order'],
                'unique_together': {('enrollment', 'chapter')},
            },
        ),
    ]
