# Generated by Django 3.2.24 on 2026-05-22 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('account', models.CharField(max_length=50, unique=True, verbose_name='学号/账号')),
                ('username', models.CharField(max_length=100, verbose_name='用户名/姓名')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('is_active', models.IntegerField(default=0, verbose_name='是否激活(0未激活/1已激活)')),
                ('role', models.IntegerField(default=1, verbose_name='角色(1=学员, 2=管理员)')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间')),
                ('activation_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='6位激活码')),
                ('activation_expire', models.DateTimeField(blank=True, null=True, verbose_name='激活码过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '实验室用户',
                'verbose_name_plural': '实验室用户',
            },
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_set_name', models.CharField(max_length=200, verbose_name='数据集名称')),
                ('data_set_desc', models.TextField(blank=True, null=True, verbose_name='数据集描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '数据集',
                'verbose_name_plural': '数据集',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='部门名称')),
                ('intro', models.TextField(blank=True, null=True, verbose_name='部门介绍')),
                ('tech_stack', models.CharField(blank=True, max_length=255, null=True, verbose_name='技术栈')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
            },
        ),
        migrations.CreateModel(
            name='LabConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='实验室名称')),
                ('intro', models.TextField(blank=True, null=True, verbose_name='实验室介绍')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='实验室地址')),
                ('contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='联系人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '实验室配置',
                'verbose_name_plural': '实验室配置',
            },
        ),
        migrations.CreateModel(
            name='LabModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200, verbose_name='模型名称')),
                ('model_desc', models.TextField(blank=True, null=True, verbose_name='模型描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AI模型',
                'verbose_name_plural': 'AI模型',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('train_params', models.JSONField(blank=True, null=True, verbose_name='训练参数')),
                ('submit_desc', models.TextField(blank=True, null=True, verbose_name='提交描述')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('task_status', models.CharField(choices=[('pending', '待执行'), ('running', '运行中'), ('completed', '已完成'), ('failed', '失败')], max_length=20, verbose_name='任务状态')),
                ('progress', models.IntegerField(default=0, verbose_name='进度(%)')),
                ('compute_resource', models.CharField(blank=True, max_length=100, null=True, verbose_name='计算资源')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('data_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.dataset', verbose_name='数据集')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.labmodel', verbose_name='关联模型')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
            },
        ),
        migrations.CreateModel(
            name='TrainingWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_name', models.CharField(max_length=100, verbose_name='周次名称')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('is_published', models.BooleanField(default=False, verbose_name='是否发布')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '培训周次',
                'verbose_name_plural': '培训周次',
            },
        ),
        migrations.CreateModel(
            name='TrainingNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='通知标题')),
                ('content', models.TextField(verbose_name='通知内容')),
                ('target', models.CharField(max_length=100, verbose_name='目标群体类型')),
                ('target_ids', models.JSONField(blank=True, null=True, verbose_name='目标ID列表')),
                ('send_time_type', models.CharField(choices=[('immediate', '立即发送'), ('scheduled', '定时发送')], max_length=20, verbose_name='发送时间类型')),
                ('scheduled_time', models.DateTimeField(blank=True, null=True, verbose_name='定时发送时间')),
                ('is_draft', models.BooleanField(default=True, verbose_name='是否为草稿')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('sent', '已发送'), ('failed', '发送失败')], default='draft', max_length=20, verbose_name='状态')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '培训通知',
                'verbose_name_plural': '培训通知',
            },
        ),
        migrations.CreateModel(
            name='TokenBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(max_length=255, unique=True, verbose_name='Token JTI')),
                ('token_type', models.CharField(max_length=20, verbose_name='Token 类型(access/refresh)')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': 'Token黑名单',
                'verbose_name_plural': 'Token黑名单',
            },
        ),
        migrations.CreateModel(
            name='TaskCorrect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_status', models.CharField(choices=[('pending', '待批改'), ('corrected', '已批改')], max_length=20, verbose_name='批改状态')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='分数')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='评语')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('corrector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='批改人')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct', to='api.task', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': '任务批改',
                'verbose_name_plural': '任务批改',
            },
        ),
        migrations.CreateModel(
            name='RegistrationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='报名表标题')),
                ('reg_start_time', models.DateTimeField(verbose_name='报名开始时间')),
                ('reg_end_time', models.DateTimeField(verbose_name='报名截止时间')),
                ('is_open', models.IntegerField(default=1, verbose_name='是否开启报名(0关/1开)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.department', verbose_name='所属部门')),
            ],
            options={
                'verbose_name': '报名配置',
                'verbose_name_plural': '报名配置',
            },
        ),
        migrations.CreateModel(
            name='LabNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='新闻标题')),
                ('content', models.TextField(verbose_name='新闻内容')),
                ('cover', models.CharField(blank=True, max_length=500, null=True, verbose_name='封面图')),
                ('is_top', models.IntegerField(default=0, verbose_name='是否置顶(0否/1是)')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '新闻公告',
                'verbose_name_plural': '新闻公告',
                'ordering': ['-is_top', '-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='作业内容')),
                ('attachment', models.CharField(blank=True, max_length=500, null=True, verbose_name='附件路径')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='分数')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='批改评语')),
                ('status', models.CharField(choices=[('submitted', '已提交'), ('pending', '待批改'), ('corrected', '已批改')], max_length=20, verbose_name='作业状态')),
                ('week', models.CharField(max_length=100, verbose_name='所属周次')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '作业',
                'verbose_name_plural': '作业',
            },
        ),
        migrations.CreateModel(
            name='FormDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='设备标识')),
                ('form_type', models.CharField(max_length=100, verbose_name='表单类型')),
                ('form_data', models.JSONField(verbose_name='表单数据')),
                ('current_step', models.IntegerField(default=1, verbose_name='当前步骤')),
                ('total_steps', models.IntegerField(default=1, verbose_name='总步骤数')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.registrationconfig', verbose_name='报名配置')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '表单草稿',
                'verbose_name_plural': '表单草稿',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='问题标题')),
                ('content', models.TextField(verbose_name='问题内容')),
                ('status', models.CharField(choices=[('pending', '待回答'), ('answered', '已回答'), ('resolved', '已解决')], default='pending', max_length=20, verbose_name='问题状态')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='回答内容')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='回答时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faq_answers', to=settings.AUTH_USER_MODEL, verbose_name='回答者')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_questions', to=settings.AUTH_USER_MODEL, verbose_name='提问者')),
            ],
            options={
                'verbose_name': 'FAQ问题',
                'verbose_name_plural': 'FAQ问题',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='labuser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.department', verbose_name='所属部门'),
        ),
        migrations.AddField(
            model_name='labuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='labuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='ApplicationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('status', models.IntegerField(choices=[(1, '待审核'), (2, '已通过'), (3, '已取消'), (4, '已拒绝')], default=1, verbose_name='状态')),
                ('audit_time', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('audit_remark', models.TextField(blank=True, null=True, verbose_name='审核备注/拒绝原因')),
                ('class_name', models.CharField(max_length=100, verbose_name='班级')),
                ('academy', models.CharField(max_length=100, verbose_name='学院')),
                ('major', models.CharField(max_length=100, verbose_name='专业')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('director_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='导员姓名')),
                ('sign_reason', models.TextField(verbose_name='报名理由')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='api.registrationconfig', verbose_name='报名配置')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_form', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '报名表',
                'verbose_name_plural': '报名表',
                'unique_together': {('config', 'user')},
            },
        ),
    ]
