# Generated by Django 5.2.14 on 2026-06-01 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_admin_assignment_dataset_labconfig_labmodel_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
