# Generated by Django 3.2.24 on 2026-05-30 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auth_models'),
        ('api', '0002_auto_20260527_2040'),
    ]

    operations = [
    ]
