# Generated by Django 3.2.24 on 2026-05-28 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20260522_1446'),
        ('api', '0002_auto_20260527_2040'),
    ]

    operations = [
    ]
