# Generated by Django 5.2.14 on 2026-05-31 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_notice_question_questionreply_systemconfig'),
        ('api', '0003_add_new_models'),
    ]

    operations = [
    ]
