# Generated by Django 3.2.24 on 2026-05-31 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_merge_0002_auto_20260522_1446_0002_auto_20260527_2040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': '部门', 'verbose_name_plural': '部门'},
        ),
        migrations.AddField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='department',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AddField(
            model_name='department',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='排序顺序'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='部门名称'),
        ),
    ]
