# Generated by Django 5.2.14 on 2026-06-01 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataarchive',
            name='operator',
            field=models.ForeignKey(blank=True, help_text='执行存档操作的用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archives', to='api.admin', verbose_name='存档人'),
        ),
    ]
