# Generated by Django 3.2.24 on 2026-05-30 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20260530_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='exam_direction',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='报考方向'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student_class',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='班级'),
        ),
        migrations.AddField(
            model_name='enrollmentdraft',
            name='exam_direction',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='报考方向'),
        ),
        migrations.AddField(
            model_name='enrollmentdraft',
            name='student_class',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='班级'),
        ),
        migrations.AddField(
            model_name='labuser',
            name='exam_direction',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='报考方向'),
        ),
        migrations.AddField(
            model_name='labuser',
            name='student_class',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='班级'),
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='批次名称')),
                ('batch_type', models.CharField(choices=[('new_student', '新生报名'), ('supplementary', '补录报名'), ('transfer', '转专业报名'), ('other', '其他')], default='new_student', max_length=50, verbose_name='批次类型')),
                ('description', models.TextField(blank=True, verbose_name='批次说明')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='截止时间')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('open', '报名中'), ('closed', '已截止'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('max_enrollments', models.IntegerField(default=0, verbose_name='最大报名人数(0为不限)')),
                ('enrolled_count', models.IntegerField(default=0, verbose_name='已报名人数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_batches', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '批次',
                'verbose_name_plural': '批次',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='api.batch', verbose_name='所属批次'),
        ),
        migrations.AddField(
            model_name='enrollmentdraft',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='api.batch', verbose_name='所属批次'),
        ),
        migrations.AddField(
            model_name='enrollmentfile',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.batch', verbose_name='所属批次'),
        ),
    ]
