# Generated by Django 5.2.14 on 2026-05-31 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merge_20260531_2037'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemConfig',
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-is_pinned', '-published_at'], 'verbose_name': '公告', 'verbose_name_plural': '公告'},
        ),
        migrations.RemoveField(
            model_name='notice',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='status',
        ),
        migrations.AddField(
            model_name='notice',
            name='author',
            field=models.ForeignKey(help_text='发布公告的管理员', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to='api.admin', verbose_name='发布人'),
        ),
        migrations.AddField(
            model_name='notice',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='公告是否置顶显示', verbose_name='是否置顶'),
        ),
        migrations.AddField(
            model_name='notice',
            name='is_published',
            field=models.BooleanField(default=False, help_text='公告是否已发布', verbose_name='是否发布'),
        ),
        migrations.AddField(
            model_name='notice',
            name='notice_type',
            field=models.CharField(choices=[('announcement', '公告'), ('notice', '通知'), ('urgent', '紧急通知')], default='notice', help_text='公告类型', max_length=20, verbose_name='公告类型'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=models.TextField(help_text='公告内容', verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='公告发布时间', null=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(help_text='公告标题', max_length=200, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='question',
            name='attachments',
            field=models.JSONField(blank=True, default=list, help_text='问题相关附件的URL列表，JSON格式存储', verbose_name='附件列表'),
        ),
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(help_text='提问用户的外键关联', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.user', verbose_name='提问者'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('technical', '技术问题'), ('environment', '环境问题'), ('process', '流程问题'), ('other', '其他')], default='other', help_text='问题分类：技术问题/环境问题/流程问题/其他', max_length=20, verbose_name='问题分类'),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(help_text='问题的详细描述', verbose_name='问题内容'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='问题创建时间，自动生成', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('pending', '未回复'), ('replied', '已回复'), ('resolved', '已解决')], default='pending', help_text='问题处理状态：未回复/已回复/已解决', max_length=20, verbose_name='问题状态'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(help_text='问题的简短标题，便于快速浏览', max_length=200, verbose_name='问题标题'),
        ),
        migrations.AlterField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='问题最后更新时间，自动更新', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='questionreply',
            name='author',
            field=models.ForeignKey(help_text='回复用户的外键关联', on_delete=django.db.models.deletion.CASCADE, related_name='question_replies', to='api.user', verbose_name='回复者'),
        ),
        migrations.AlterField(
            model_name='questionreply',
            name='content',
            field=models.TextField(help_text='回复的详细内容', verbose_name='回复内容'),
        ),
        migrations.AlterField(
            model_name='questionreply',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='回复创建时间，自动生成', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='questionreply',
            name='question',
            field=models.ForeignKey(help_text='关联的问题外键', on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.question', verbose_name='所属问题'),
        ),
        migrations.AlterField(
            model_name='questionreply',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='回复最后更新时间，自动更新', verbose_name='更新时间'),
        ),
        migrations.AlterModelTable(
            name='notice',
            table='notices',
        ),
        migrations.AlterModelTable(
            name='question',
            table='questions',
        ),
        migrations.AlterModelTable(
            name='questionreply',
            table='question_replies',
        ),
    ]
