# Generated by Django 3.2.24 on 2026-05-31 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_systemconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['sort_order', '-created_at'], 'verbose_name': 'FAQ问题', 'verbose_name_plural': 'FAQ问题'},
        ),
        migrations.AlterModelOptions(
            name='labnews',
            options={'ordering': ['-is_pinned', '-pin_time', '-created_at'], 'verbose_name': '新闻公告', 'verbose_name_plural': '新闻公告'},
        ),
        migrations.RemoveField(
            model_name='labnews',
            name='is_top',
        ),
        migrations.AddField(
            model_name='faq',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='删除时间'),
        ),
        migrations.AddField(
            model_name='faq',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='faq',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='排序权重'),
        ),
        migrations.AddField(
            model_name='labnews',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='是否置顶'),
        ),
        migrations.AddField(
            model_name='labnews',
            name='pin_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='置顶时间'),
        ),
        migrations.AddField(
            model_name='labnews',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('withdrawn', '已撤回')], default='draft', max_length=20, verbose_name='状态'),
        ),
    ]
