# Generated by Django 3.2.24 on 2026-05-31 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20260531_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingnotification',
            name='training_week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.trainingweek', verbose_name='关联周次'),
        ),
        migrations.AddField(
            model_name='trainingweek',
            name='instructors',
            field=models.ManyToManyField(blank=True, related_name='teaching_weeks', to=settings.AUTH_USER_MODEL, verbose_name='讲师/助教'),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='作业标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='作业描述')),
                ('deadline', models.DateTimeField(verbose_name='截止时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_assignments', to=settings.AUTH_USER_MODEL, verbose_name='发布人')),
                ('training_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.trainingweek', verbose_name='关联周次')),
            ],
            options={
                'verbose_name': '作业任务',
                'verbose_name_plural': '作业任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(auto_now_add=True, verbose_name='签到时间')),
                ('status', models.CharField(choices=[('present', '已签到'), ('absent', '未签到'), ('late', '迟到')], default='present', max_length=20, verbose_name='签到状态')),
                ('training_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='api.trainingweek', verbose_name='关联周次')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL, verbose_name='签到人')),
            ],
            options={
                'verbose_name': '培训签到',
                'verbose_name_plural': '培训签到',
                'unique_together': {('training_week', 'user')},
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='提交内容')),
                ('attachment', models.CharField(blank=True, max_length=500, null=True, verbose_name='附件路径')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='分数')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='批改评语')),
                ('status', models.CharField(choices=[('submitted', '已提交'), ('pending', '待批改'), ('corrected', '已批改')], default='submitted', max_length=20, verbose_name='提交状态')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='api.assignment', verbose_name='所属作业')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
            ],
            options={
                'verbose_name': '作业提交',
                'verbose_name_plural': '作业提交',
                'unique_together': {('assignment', 'user')},
            },
        ),
    ]
