# Generated by Django 3.2.24 on 2026-05-31 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20260530_1931'),
        ('api', '0008_auto_20260531_1737'),
    ]

    operations = [
    ]
